namespace FinanceBot.Domain;

public enum AccountType { Bank, Cash, Other }
public enum TransactionType { Expense, Income, Transfer, BalanceAdjustment, DebtSettlement }
public enum DebtDirection { Payable, Receivable }
public enum DebtStatus { Open, Settled, Cancelled }
public enum BatchStatus { Collecting, Processing, Completed, Failed, NeedsReview }
public enum InputMessageType { Text, Photo, Voice }
public enum RunStatus { Running, Completed, Failed }
public enum ValidationStatus { Pass, Fail }
public enum CategoryType { Expense, Income }

public abstract class Entity { public long Id { get; set; } }
public sealed class User : Entity { public long TelegramUserId { get; set; } public string Name { get; set; } = ""; public DateTimeOffset CreatedAt { get; set; } }
public sealed class Account : Entity { public string Name { get; set; } = ""; public string CurrencyCode { get; set; } = "MYR"; public AccountType Type { get; set; } public long? OwnerUserId { get; set; } public User? OwnerUser { get; set; } public bool IsActive { get; set; } = true; public DateTimeOffset CreatedAt { get; set; } }
public sealed class Category : Entity { public string Name { get; set; } = ""; public long? ParentId { get; set; } public Category? Parent { get; set; } public CategoryType Type { get; set; } public bool IsActive { get; set; } = true; }
public sealed class InputBatch : Entity { public long UserId { get; set; } public User User { get; set; } = null!; public DateTimeOffset StartedAt { get; set; } public DateTimeOffset LastMessageAt { get; set; } public DateTimeOffset? ProcessingStartedAt { get; set; } public DateTimeOffset? CompletedAt { get; set; } public BatchStatus Status { get; set; } public List<InputMessage> Messages { get; set; } = []; }
public sealed class InputMessage : Entity { public long InputBatchId { get; set; } public InputBatch InputBatch { get; set; } = null!; public long TelegramMessageId { get; set; } public InputMessageType Type { get; set; } public string? Text { get; set; } public string? Transcript { get; set; } public string? TelegramFileId { get; set; } public DateTimeOffset CreatedAt { get; set; } }
public sealed class Transaction : Entity { public long CreatedByUserId { get; set; } public User CreatedByUser { get; set; } = null!; public TransactionType Type { get; set; } public DateTimeOffset TransactionDate { get; set; } public string CurrencyCode { get; set; } = "MYR"; public decimal Amount { get; set; } public string Description { get; set; } = ""; public string? MerchantName { get; set; } public long? CategoryId { get; set; } public Category? Category { get; set; } public long? InputBatchId { get; set; } public DateTimeOffset CreatedAt { get; set; } public DateTimeOffset UpdatedAt { get; set; } public List<AccountMovement> Movements { get; set; } = []; }
public sealed class AccountMovement : Entity { public long TransactionId { get; set; } public Transaction Transaction { get; set; } = null!; public long AccountId { get; set; } public Account Account { get; set; } = null!; public decimal Amount { get; set; } }
public sealed class ExchangeDetail { public long TransactionId { get; set; } public Transaction Transaction { get; set; } = null!; public decimal FromAmount { get; set; } public string FromCurrency { get; set; } = ""; public decimal ToAmount { get; set; } public string ToCurrency { get; set; } = ""; public decimal ExchangeRate { get; set; } }
public sealed class Receipt : Entity { public long TransactionId { get; set; } public Transaction Transaction { get; set; } = null!; public string MerchantName { get; set; } = ""; public DateTimeOffset? ReceiptDate { get; set; } public decimal Subtotal { get; set; } public decimal Tax { get; set; } public decimal ServiceCharge { get; set; } public decimal Discount { get; set; } public decimal Rounding { get; set; } public decimal Total { get; set; } public string CurrencyCode { get; set; } = ""; public string RawExtractedJson { get; set; } = "{}"; public List<ReceiptItem> Items { get; set; } = []; }
public sealed class ReceiptItem : Entity { public long ReceiptId { get; set; } public Receipt Receipt { get; set; } = null!; public string RawName { get; set; } = ""; public string NormalizedName { get; set; } = ""; public decimal Quantity { get; set; } public decimal UnitPrice { get; set; } public decimal BaseAmount { get; set; } public decimal Discount { get; set; } public decimal TaxAllocated { get; set; } public decimal ServiceChargeAllocated { get; set; } public decimal FinalAmount { get; set; } public long? CategoryId { get; set; } public Category? Category { get; set; } public decimal AiConfidence { get; set; } public bool WasUserCorrected { get; set; } }
public sealed class Debt : Entity { public long CreatedByUserId { get; set; } public DebtDirection Direction { get; set; } public string Counterparty { get; set; } = ""; public string CurrencyCode { get; set; } = ""; public decimal OriginalAmount { get; set; } public string Description { get; set; } = ""; public DateTimeOffset CreatedAt { get; set; } public DebtStatus Status { get; set; } public List<DebtPayment> Payments { get; set; } = []; }
public sealed class DebtPayment : Entity { public long DebtId { get; set; } public Debt Debt { get; set; } = null!; public long TransactionId { get; set; } public Transaction Transaction { get; set; } = null!; public decimal Amount { get; set; } public DateTimeOffset PaidAt { get; set; } }
public sealed class AiRun : Entity { public long InputBatchId { get; set; } public string Model { get; set; } = ""; public string PromptVersion { get; set; } = "v1"; public string InputJson { get; set; } = ""; public string? OutputJson { get; set; } public DateTimeOffset StartedAt { get; set; } public DateTimeOffset? CompletedAt { get; set; } public RunStatus Status { get; set; } public string? Error { get; set; } public List<ValidationResult> ValidationResults { get; set; } = []; }
public sealed class ValidationResult : Entity { public long AiRunId { get; set; } public AiRun AiRun { get; set; } = null!; public string Type { get; set; } = ""; public decimal? ExpectedValue { get; set; } public decimal? ActualValue { get; set; } public decimal? Difference { get; set; } public ValidationStatus Status { get; set; } public string Message { get; set; } = ""; }
public sealed class AuditLog : Entity { public string EntityType { get; set; } = ""; public long EntityId { get; set; } public string Action { get; set; } = ""; public string? OldJson { get; set; } public string? NewJson { get; set; } public long UserId { get; set; } public DateTimeOffset CreatedAt { get; set; } }
