<Project Sdk="Microsoft.NET.Sdk.Worker"><ItemGroup><ProjectReference Include="../FinanceBot.Infrastructure/FinanceBot.Infrastructure.csproj" /><PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" /><PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" /><PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" /><PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" /><PackageReference Include="Serilog.Sinks.File" Version="6.0.0" /></ItemGroup><ItemGroup><None Update="appsettings.json"><CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory></None></ItemGroup></Project>
